repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Cleanup trailing whitespaces
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.86.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_trivy
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
  # - repo: https://github.com/terraform-docs/terraform-docs
  #   rev: "v0.17.0"
  #   hooks:
  #     - id: terraform-docs-go
  #       args:
  #         - "-c"
  #         - ".terraform-docs.yml"
  #         - "."
